services:
  api:
    build: .
    command: ["/app/api"]
    environment:
      HTTP_ADDR: ":8080"
      MYSQL_DSN: "inventory:inventory@tcp(mysql:3306)/inventory_cache?parseTime=true&multiStatements=true"
      REDIS_ADDR: "redis:6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      API_INTERNAL_BASE_URL: "http://api:8080"
      L1_TTL_SECONDS: "5"
      L2_TTL_SECONDS: "60"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    command: ["/app/worker"]
    environment:
      REDIS_ADDR: "redis:6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      API_INTERNAL_BASE_URL: "http://api:8080"
      L2_TTL_SECONDS: "60"
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: inventory_cache
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  mysql-data:
